CREATE TABLE [dbo].[Mods]
(
	[Id] VARCHAR(50) NOT NULL PRIMARY KEY, 
    [ItemID] VARCHAR(50) NOT NULL FOREIGN KEY REFERENCES Item(Id), 
    [ModType] VARCHAR(50) NOT NULL, 
    [Value] VARCHAR(50) NULL
)
